name: BUILD TEST

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Source Code with Submodules (JDK 17)
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
        fetch-depth: 0
        java-version: '17'
        distribution: 'temurin'
        
    - name: Move Submodule to src/main/resources
      run: |
        cp -r business-card-config/* src/main/resources/
        
    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    #- name: Run Tests
    #  run: ./gradlew test
