name: BUILD TEST

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Source Code with Submodules
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Move Submodule to src/main/resources
      run: |
        cp -r business-card-config/* src/main/resources/

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew --no-daemon clean build
